import Navigation from "./components/navigation/navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./styles/page.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={styles.header}>
          <h1 className={styles.companyName}>Made By Omega</h1>
        </header>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
