import Navigation from "./components/navigation/navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css';
import styles from "./styles/page.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Made by Omega",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <header className={styles.header}>
          <h1 className={styles.companyName}>Made By Omega</h1> <Navigation/>
        </header>
        <section className={styles.main}>
          {children}
        </section>
        <footer className={styles.footer}>
          <p>© 2024 Made By Omega. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
